version: "3.3"

services:
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - db-net

  app:
    build: .
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    networks:
      - db-net

networks:
  db-net:
    driver: bridge
